var district = [
    {
        url:'https://coronaharyana.in/?city=1',
        name:'ambala'
    },
    {
        url:'https://coronaharyana.in/?city=2',
        name:'bhiwani'
    },
    {
        url:'https://coronaharyana.in/?city=24',
        name:'chandigarh'
    },
    {
        url:'https://coronaharyana.in/?city=3',
        name:'charkidadri'
    },
    {
        url:'https://coronaharyana.in/?city=4',
        name:'faridabad'
    },
    {
        url:'https://coronaharyana.in/?city=5',
        name:'fatehabad'
    },
    {
        url:'https://coronaharyana.in/?city=6',
        name:'gurugram'
    },
    {
        url:'https://coronaharyana.in/?city=7',
        name:'hisar'
    },
    {
        url:'https://coronaharyana.in/?city=8',
        name:'jhajjar'
    },
    {
        url:'https://coronaharyana.in/?city=9',
        name:'jind'
    },
    {
        url:'https://coronaharyana.in/?city=10',
        name:'kaithal'
    },
    {
        url:'https://coronaharyana.in/?city=11',
        name:'karnal'
    },
    {
        url:'https://coronaharyana.in/?city=12',
        name:'kurukshetra'
    },
    {
        url:'https://coronaharyana.in/?city=13',
        name:'mahendragarh'
    },
    {
        url:'https://coronaharyana.in/?city=14',
        name:'ambala'
    },
    {
        url:'https://coronaharyana.in/?city=23',
        name:'nuh'
    },
    {
        url:'https://coronaharyana.in/?city=15',
        name:'palwal'
    },
    {
        url:'https://coronaharyana.in/?city=16',
        name:'panchkula'
    },
    {
        url:'https://coronaharyana.in/?city=17',
        name:'panipat'
    },
    {
        url:'https://coronaharyana.in/?city=18',
        name:'rewari'
    },
    {
        url:'https://coronaharyana.in/?city=19',
        name:'rohtak'
    },
    {
        url:'https://coronaharyana.in/?city=20',
        name:'sirsa'
    },
    {
        url:'https://coronaharyana.in/?city=21',
        name:'sonipat'
    },
    {
        url:'https://coronaharyana.in/?city=22',
        name:'yamunanagar'
    }

]


exports.haryana = district